Repository FRONTENDSCHOOL8/Book-Kong, pull requests merged in 2024-03, with the labels that each got.

#112 Feature/109 data load
  src/components/organisms/GlobalNavigator.jsx
  src/utils/controlBookData.js
  src/utils/controlUserData.js
Labels: 💎Feature

#113 Feature/62 gnb markup
  src/components/organisms/GlobalNavigator.jsx
  src/styles/tailwind.css
Labels: 🖌️ Markup

#122 [Modify] pocketbase collection 이름 변경에 따른 코드 변경
  src/utils/controlBookData.js
Labels: 📁 Chore

#126 [Build] Storybook 실행 코드와 Storybook 관련 packages 설치 코드 추가, Storybook 관련 ESLint 설정 추가 외
  .eslintrc.cjs
  .storybook/main.js
  .storybook/preview.js
  package.json
  pnpm-lock.yaml
Labels: 📁 Chore

#128 Feature/storybook bugfix
  .storybook/main.js
  .storybook/preview.js
  package.json
  pnpm-lock.yaml
  src/components/organisms/GlobalNavigator/GlobalNavigator.stories.js
Labels: 💊 BugFix

#131 기록 페이지 MarkUp
  package.json
  pnpm-lock.yaml
  public/images/icons/addBook.svg
  public/images/icons/before.svg
  public/images/icons/books.svg
  public/images/icons/check.svg
  public/images/icons/delete.svg
  public/images/icons/done.svg
  public/images/icons/heart=heart3.svg
  public/images/icons/memo.svg
  public/images/icons/more_horizontal.svg
  public/images/icons/more_vertical.svg
  public/images/icons/newBook.svg
  public/images/icons/newrecord.svg
  public/images/icons/openBook.svg
  public/images/icons/order.svg
  public/images/icons/reading.svg
  public/images/icons/star=star3.svg
  src/Router.jsx
  src/components/atoms/AddBookIconButton/AddBookIconButton.jsx
  src/components/atoms/AddBookIconButton/AddBookIconButton.stories.js
  src/components/atoms/Back/Back.jsx
  src/components/atoms/Back/Back.stories.js
  src/components/atoms/DeleteIconButton/DeleteIconButton.jsx
  src/components/atoms/DeleteIconButton/DeleteIconButton.stories.js
  src/components/atoms/LargeHeaderIcon/LargeHeaderIcon.jsx
  src/components/atoms/LargeHeaderIcon/LargeHeaderIcon.stories.js
  src/components/atoms/LargeHeaderTitle/LargeHeaderTitle.jsx
  src/components/atoms/LargeHeaderTitle/LargeHeaderTitle.stories.js
  src/components/atoms/SaveButton/SaveButton.jsx
  src/components/atoms/SaveButton/SaveButton.stories.js
  src/components/atoms/SmallHeaderTitle/SmallHeaderTitle.jsx
  src/components/atoms/SmallHeaderTitle/SmallHeaderTitle.stories.js
  src/components/atoms/WriteMemoIconButton/WriteMemoIconButton.jsx
  src/components/atoms/WriteMemoIconButton/WriteMemoIconButton.stories.js
  src/components/organisms/GlobalNavigator/GlobalNavigator.jsx
  src/components/organisms/Header/LargeHeader/LargeHeader.jsx
  src/components/organisms/Header/LargeHeader/LargeHeader.stories.js
  src/components/organisms/Header/SmallHeader/SmallHeader.jsx
  src/components/organisms/Header/SmallHeader/SmallHeader.stories.js
  src/components/pages/Character.jsx
  src/components/pages/CharacterPage.jsx
  src/components/pages/Feed.jsx
  src/components/pages/FeedPage.jsx
  src/components/pages/Library.jsx
  src/components/pages/LibraryPage.jsx
  src/components/pages/Mypage.jsx
  src/components/pages/MypagePage.jsx
  src/components/pages/Record.jsx
  src/components/pages/RecordPage.jsx
  src/styles/tailwind.css
  tailwind.config.js
Labels: 💎Feature

#135 기록 페이지 데이터 통신 및 정렬 기능 구현
  src/Router.jsx
  src/components/atoms/ContextButtonVertical/ContextButtonVertical.jsx
  src/components/atoms/MemoContents/MemoContents.jsx
  src/components/atoms/MemoDate/MemoDate.jsx
  src/components/atoms/TabButton/TabButton.jsx
  src/components/molecules/OrderButton/OrderButton.jsx
  src/components/molecules/RecordTitle/RecordTitle.jsx
  src/components/organisms/GlobalNavigator/GlobalNavigator.jsx
  src/components/organisms/MemoCard/MemoCard.jsx
  src/components/organisms/MemoList/MemoList.jsx
  src/components/organisms/TabNavigation/TabNavigation.jsx
  src/components/pages/LibraryPage.jsx
  src/components/pages/RecordPage.jsx
  src/utils/controlMemoData.js
Labels: 💎Feature, 🔴 Priority: Critical

#136 기록 페이지 애니메이션
  package.json
  pnpm-lock.yaml
  src/components/organisms/MemoCard/MemoCard.jsx
  src/components/organisms/MemoList/MemoList.jsx
  src/utils/convertDayFormat.js
Labels: 💎Feature

#138 API를 통해 책 정보 화면에 출력하기
  package.json
  pnpm-lock.yaml
  src/api/searchAladin.js
  src/app/App.jsx
  src/components/atoms/InputBar/InputBar.jsx
  src/components/atoms/SearchButton/SearchButton.jsx
  src/components/atoms/SearchCount/SearchCount.jsx
  src/components/molecules/SearchBar/SearchBar.jsx
  src/components/molecules/SearchCard/SearchCard.jsx
  src/components/organisms/Header/LargeHeader/LargeHeader.jsx
  src/components/organisms/Header/SmallHeader/SmallHeader.jsx
  src/components/organisms/MemoList/MemoList.jsx
  src/components/organisms/SearchList/SearchList.jsx
  src/components/organisms/SearchMainContents/SearchMainContents.jsx
  src/components/organisms/TabNavigation/TabNavigation.jsx
  src/styles/tailwind.css
Labels: 💎Feature, 🔴 Priority: Critical

#140 [Feat] A11yHidden 유틸 컴포넌트, checkPbDuplication 유틸 함수 생성 외
  src/components/atoms/A11yHidden/A11yHidden.jsx
  src/components/atoms/A11yHidden/A11yHidden.stories.js
  src/hooks/index.js
  src/hooks/useReference.js
  src/hooks/useTilt.js
  src/hooks/useTime.js
  src/utils/CustomPropTypes.js
  src/utils/checkPbDuplication.js
  src/utils/index.js
  src/utils/typeIs.js
Labels: 💎Feature

#141 책 검색 페이지의 카드 클릭시 해당 데이터를 화면에 랜더링 하는 기능 구현
  src/Router.jsx
  src/app/App.jsx
  src/components/atoms/AddBookIconButton/AddBookIconButton.jsx
  src/components/atoms/BookInfoImage/BookInfoImage.jsx
  src/components/molecules/BookInfoInput/BookInfoInput.jsx
  src/components/molecules/SearchCard/SearchCard.jsx
  src/components/organisms/BookInfoList/BookInfoList.jsx
  src/components/organisms/Header/SmallHeader/SmallHeader.jsx
  src/components/pages/BookRegistrationPage.jsx
  src/utils/getRandomNumber.js
Labels: 💎Feature, 🔴 Priority: Critical

#142 [Feat] 회원가입 기능구현, 마크업, 데이터전송
  public/images/etc/bg-1px.png
  public/images/icons/apple_icon.svg
  public/images/icons/facebook_icon.svg
  public/images/icons/kakao_icon.svg
  public/images/icons/naver_icon.svg
  public/images/icons/password-eye.svg
  public/images/icons/state=hidden.svg
  src/Router.jsx
  src/components/pages/Register.jsx
Labels: 💎Feature, 🔴 Priority: Critical

#143 누적 페이지를 이용한 책 쌓기 구현, 사용자가 읽은 책의 총 권수와 cm 기능 구현
  src/Router.jsx
  src/components/atoms/BookBlock/BookBlock.jsx
  src/components/atoms/BookBlock/BookBlock.stories.js
  src/components/atoms/SaveBookImg/SaveBookImg.jsx
  src/components/atoms/SaveBookImg/SaveBookImg.stories.js
  src/components/atoms/TotalBookCount/TotalBookCount.jsx
  src/components/atoms/TotalBookCount/TotalBookCount.stories.js
  src/components/atoms/TotalBookHeight/TotalBookHeight.jsx
  src/components/atoms/TotalBookHeight/TotalBookHeight.stories.js
  src/components/molecules/BookBlockList/BookBlockList.jsx
  src/components/molecules/BookBlockList/BookBlockList.stories.js
  src/components/molecules/BookInfo/BookInfo.jsx
  src/components/molecules/BookInfo/BookInfo.stories.js
  src/components/organisms/BookTree/BookTree.jsx
  src/components/organisms/BookTree/BookTree.stories.js
  src/components/subatoms/BookTitle/BookTitle.jsx
  src/components/subatoms/BookTitle/BookTitle.stories.js
  src/styles/tailwind.css
  tailwind.config.js
Labels: 💎Feature, 🔴 Priority: Critical

#149 [Feat] 시작일/완독일을 입력할 수 있는 Input component 개발 외
  index.html
  public/images/icons/heart=default.svg
  public/images/icons/heart=heart3.svg
  public/images/icons/heart=selected.svg
  public/images/icons/star=default.svg
  public/images/icons/star=selected.svg
  public/images/icons/star=star3.svg
  src/components/atoms/A11yHidden/A11yHidden.jsx
  src/components/atoms/A11yHidden/A11yHidden.stories.js
  src/components/atoms/Label/Label.jsx
  src/components/atoms/Label/Label.stories.js
  src/components/molecules/InputContainer/InputContainer.jsx
  src/components/molecules/InputContainer/InputContainer.stories.js
  src/utils/storybook.js
Labels: 💎Feature

#152 책장 탭 렌더링 기능 구현
  package.json
  pnpm-lock.yaml
  public/images/rate/after/afterrate=1.png
  public/images/rate/after/afterrate=2.png
  public/images/rate/after/afterrate=3.png
  public/images/rate/after/afterrate=4.png
  public/images/rate/after/afterrate=5.png
  public/images/rate/before/beforerate=1.png
  public/images/rate/before/beforerate=2.png
  public/images/rate/before/beforerate=3.png
  public/images/rate/before/beforerate=4.png
  public/images/rate/before/beforerate=5.png
  src/Router.jsx
  src/components/atoms/CardImage/CardImage.jsx
  src/components/atoms/SearchCount/SearchCount.jsx
  src/components/molecules/Card/Card.jsx
  src/components/molecules/CardInfo/CardInfo.jsx
  src/components/molecules/SearchCard/SearchCard.jsx
  src/components/organisms/Bookshelf/Bookshelf.jsx
  src/components/organisms/List/List.jsx
  src/components/organisms/SearchMainContents/SearchMainContents.jsx
  src/main.jsx
  src/styles/tailwind.css
  src/utils/getPbImage.js
Labels: 💎Feature, 🔴 Priority: Critical

#157 책장 카테고리 필터링 기능 구현
  src/components/atoms/FilterIcon/FilterIcon.jsx
  src/components/molecules/Filter/Filter.jsx
  src/components/molecules/RateContainer/RateContainer.jsx
  src/components/molecules/RateContainer/RateContainer.stories.js
  src/components/organisms/Bookshelf/Bookshelf.jsx
Labels: 💎Feature, 🔴 Priority: Critical

#158 책장 내 검색 기능 구현
  src/components/atoms/BookInfoImage/BookInfoImage.jsx
  src/components/molecules/SearchBar/SearchBar.jsx
  src/components/organisms/Bookshelf/Bookshelf.jsx
  src/components/organisms/SearchMainContents/SearchMainContents.jsx
  src/utils/controlBookData.js
Labels: 💎Feature, 🔴 Priority: Critical

#160 피드 페이지 레이아웃 버그 해결 및 유저 정보 렌더링 기능 구현
  src/components/organisms/FeedCard/FeedCard.jsx
  src/components/organisms/FeedList/FeedList.jsx
  src/styles/tailwind.css
  src/utils/controlFeedData.js
Labels: 💊 BugFix, 🔴 Priority: Critical

#164 [Feat] 최초 페이지 설정 및 비로그인 상태시 로그인 페이지로 이동
  package.json
  pnpm-lock.yaml
  src/Router.jsx
  src/app/App.jsx
  src/components/organisms/BookTree/BookTree.jsx
  src/components/organisms/Bookshelf/Bookshelf.jsx
  src/components/organisms/MemoList/MemoList.jsx
  src/components/pages/BookRegistrationPage.jsx
  src/components/pages/CharacterPage.jsx
  src/components/pages/DetailPage.jsx
  src/components/pages/FeedPage.jsx
  src/components/pages/LibraryPage.jsx
  src/components/pages/Login.jsx
  src/components/pages/MypagePage.jsx
  src/components/pages/RecordPage.jsx
  src/components/pages/Register.jsx
  src/components/pages/SearchPage.jsx
Labels: 💎Feature, 🔴 Priority: Critical

#166 [Feat] 마이페이지 구현
  src/Router.jsx
  src/app/App.jsx
  src/components/organisms/Bookshelf/Bookshelf.jsx
  src/components/pages/MypagePage.jsx
  src/components/pages/Register.jsx
  src/utils/controlUserData.js
Labels: 💎Feature, 🔴 Priority: Critical
