Repository FRONTENDSCHOOL8/Book-Kong, pull requests merged in 2024-06, with the labels that each got.

#195 Feature/179 feed detail markup
  public/images/characters/Rectangle 99.png
  public/images/icons/arrow-up.svg
  public/images/icons/newrecord-black.svg
  src/Router.jsx
  src/components/atoms/LargeHeaderIcon/LargeHeaderIcon.jsx
  src/components/atoms/SignupButton/SignupButton.stories.js
  src/components/atoms/SmallHeaderTitle/SmallHeaderTitle.jsx
  src/components/molecules/BookCardInfo/BookCardInfo.stories.js
  src/components/molecules/FeedDetailCommentContents/FeedDetailCommentContents.jsx
  src/components/molecules/FeedDetailCommentContents/FeedDetailCommentContents.stories.js
  src/components/molecules/FeedDetailPostContents/FeedDetailPostContents.jsx
  src/components/molecules/FeedDetailPostContents/FeedDetailPostContents.stories.js
  src/components/organisms/FeedCard/FeedCard.jsx
  src/components/organisms/FeedDetailContents/FeedDetailContents.jsx
  src/components/organisms/FeedDetailContents/FeedDetailContents.stories.js
  src/components/organisms/Header/Header/Header.jsx
  src/components/organisms/Header/SmallHeader/SmallHeader.jsx
  src/components/pages/FeedDetailPage/FeedDetailPage.jsx
  src/components/pages/FeedDetailPage/FeedDetailPage.stories.js
Labels: 🔴 Priority: Critical, 🖌️ Markup

#194 Feature/101 feed registration
  package.json
  pnpm-lock.yaml
  src/Router.jsx
  src/components/atoms/LargeHeaderIcon/LargeHeaderIcon.jsx
  src/components/organisms/FeedList/FeedList.jsx
  src/components/organisms/Header/Header/Header.jsx
  src/components/pages/FeedRegistrationPage/FeedRegistrationPage.jsx
  src/components/pages/FeedRegistrationPage/FeedRegistrationPage.stories.js
  src/main.jsx
Labels: 💎Feature, 🔴 Priority: Critical

#190 Feature/177 memo page
  src/Router.jsx
  src/components/organisms/Header/Header/Header.jsx
  src/components/organisms/MemoCard/MemoCard.jsx
  src/components/organisms/MemoList/MemoList.jsx
  src/components/pages/MemoDetailPage/MemoDetailPage.jsx
  src/components/pages/MemoDetailPage/MemoDetailPage.stories.js
Labels: 💎Feature
