Repository FRONTENDSCHOOL8/Book-Kong, pull requests merged in 2024-11, with the labels that each got.

#203 [Feat] 메모 작성/저장 시 DB에 데이터 업로드 후 메모페이지로 복귀
  src/components/atoms/MemoDate/MemoDate.jsx
  src/components/molecules/DetailBookInfoPage/DetailBookInfoPage.jsx
  src/components/molecules/RecordTitle/RecordTitle.jsx
  src/components/pages/MemoDetailPage/MemoDetailPage.jsx
  src/components/pages/MemoRegistrationPage/MemoRegistrationPage.jsx
  src/components/pages/SplashPage/SplashPage.jsx
  src/styles/tailwind.css
  tailwind.config.js
Labels: 💎Feature, 💜 Accessibility, 📝 Modify, 📁 Chore

#208 [Feat] 책 상세페이지 탑버튼 구현 외
  public/images/icons/more_horizontal.svg
  public/images/icons/more_vertical.svg
  public/images/icons/top-button.svg
  src/components/atoms/ContextButton/ContextButton.jsx
  src/components/atoms/TopButton/TopButton.jsx
  src/components/atoms/TopButton/TopButton.stories.js
  src/components/molecules/BookDetailNavigation/BookDetailNavigation.jsx
  src/components/molecules/DetailBookInfo/DetailBookInfo.jsx
  src/components/organisms/BookTree/BookTree.jsx
  src/components/organisms/DetailBook/DetailBook.jsx
  src/components/organisms/FeedCard/FeedCard.jsx
  src/components/organisms/MemoCard/MemoCard.jsx
  src/utils/getCombinedClassName.js
Labels: 💎Feature, 🖌️ Markup, 📝 Modify, 📁 Chore

#205 [Modify] 앱 초기 접근 시 서재 페이지에 필요한 data prefetch 하는 기능 구현
  src/app/App.jsx
  src/components/organisms/BookTree/BookTree.jsx
  src/components/pages/FeedRegistrationPage/FeedRegistrationPage.jsx
  src/components/pages/MemoRegistrationPage/MemoRegistrationPage.jsx
  src/utils/controlBookData.js
Labels: 📝 Modify

#207 [Modify] 책장 및 책 검색 페이지 내 SearchBar의 style 및 검색 방식 수정, reset 버튼 추가
  package.json
  pnpm-lock.yaml
  public/images/icons/reset.svg
  src/components/atoms/ResetBtn/ResetBtn.jsx
  src/components/atoms/ResetBtn/ResetBtn.stories.js
  src/components/atoms/SearchButton/SearchButton.jsx
  src/components/atoms/SearchButton/SearchButton.stories.js
  src/components/atoms/SearchIcon/SearchIcon.jsx
  src/components/atoms/SearchIcon/SearchIcon.stories.js
  src/components/atoms/SearchInput/SearchInput.jsx
  src/components/molecules/ReadingStateFilter/ReadingStateFilter.jsx
  src/components/molecules/SearchBar/SearchBar.jsx
  src/components/molecules/UserBookCard/UserBookCard.jsx
  src/components/organisms/BookSearchMain/BookSearchMain.jsx
  src/components/organisms/Bookshelf/Bookshelf.jsx
  src/components/organisms/SearchList/SearchList.jsx
  src/components/organisms/UserBookList/UserBookList.jsx
  src/hooks/useAladinDataInit.js
  src/hooks/useUserLibData.js
  src/main.jsx
Labels: 💎Feature, 🛠️ Refactor, 🖌️ Markup, 📝 Modify, 📁 Chore

#211 [BugFix] BookTree내 BookInfo, ContextButton 레이아웃 꺠짐 스타일 수정 외
  src/components/atoms/TabButton/TabButton.jsx
  src/components/atoms/TopButton/TopButton.jsx
  src/components/atoms/TotalBookCount/TotalBookCount.jsx
  src/components/atoms/TotalBookHeight/TotalBookHeight.jsx
  src/components/molecules/BookInfo/BookInfo.jsx
  src/components/organisms/BookTree/BookTree.jsx
Labels: 💊 BugFix

#215 [BuxFix] 2차 배포 전 오류 수정 외
  src/components/atoms/BookTitle/BookTitle.jsx
  src/components/atoms/CharacterItem/CharacterItem.jsx
  src/components/atoms/FormInput/FormInput.jsx
  src/components/molecules/BookBlock/BookBlock.jsx
  src/components/molecules/BookDetailNavigation/BookDetailNavigation.jsx
  src/components/molecules/BookInfo/BookInfo.jsx
  src/components/molecules/CharacterList/CharacterList.jsx
  src/components/molecules/DetailBookInfo/DetailBookInfo.jsx
  src/components/molecules/DetailBookMemo/DetailBookMemo.jsx
  src/components/molecules/FeedDetailCommentContents/FeedDetailCommentContents.jsx
  src/components/molecules/FeedDetailPostContents/FeedDetailPostContents.jsx
  src/components/molecules/FormInputBox/FormInputBox.jsx
  src/components/molecules/UserCharacterCard/UserCharacterCard.jsx
  src/components/organisms/BookTree/BookTree.jsx
  src/components/organisms/CharacterCollection/CharacterCollection.jsx
  src/components/organisms/FeedDetailContents/FeedDetailContents.jsx
  src/components/pages/LoginPage.jsx
  src/components/pages/MypagePage.jsx
  src/components/pages/RegisterPage.jsx
  src/styles/tailwind.css
  tailwind.config.js
Labels: 💎Feature, 💊 BugFix, 💜 Accessibility, 📝 Modify, 📁 Chore

#217 [Feat] PocketBase DB 내 로그인 한 유저의 'users' collection record를 prefetch 하는 기능 추가 외
  src/Router.jsx
  src/app/App.jsx
  src/components/atoms/BookCoverInput/BookCoverInput.jsx
  src/components/atoms/PwdVisibleIcon/PwdVisibleIcon.jsx
  src/components/atoms/PwdVisibleIcon/PwdVisibleIcon.stories.js
  src/components/molecules/BookBlock/BookBlock.jsx
  src/components/molecules/SearchBar/SearchBar.jsx
  src/components/organisms/Bookshelf/Bookshelf.jsx
  src/components/organisms/CharacterCollection/CharacterCollection.jsx
  src/components/organisms/MemoList/MemoList.stories.js
  src/components/pages/MypagePage.jsx
  src/components/pages/RegisterPage.jsx
  src/hooks/useQueryWithErr.js
  src/utils/controlUserData.js
Labels: 💎Feature, 💊 BugFix, 🛠️ Refactor, 📝 Modify, 📁 Chore

#220 [Docs] README.md 업데이트
  README.md
Labels: 📄 Documentation
